dist: xenial

language: cpp

compiler: gcc

before_install:
        - sudo apt update
        - sudo apt -y install libraw-dev
        - sudo apt -y install libopencv-dev

before_script:
        - mkdir systemc
        - wget https://accellera.org/images/downloads/standards/systemc/systemc-2.3.1a.tar.gz
        - tar -xf systemc-2.3.1a.tar.gz
        - cd systemc-2.3.1a
        - mkdir objdir
        - cd objdir
        - ../configure --prefix=/usr/local/systemc-2.3.3q
        - make -j
        - sudo mkdir /usr/local/systemc-2.3.3q
        - sudo make install
        - sudo sed -i '/using std::gets;/d' /usr/local/systemc-2.3.3q/include/systemc.h
        - sudo sed -i '/using sc_dt::uint64;/d' /usr/local/systemc-2.3.3q/include/systemc.h
        - sudo sed -i '/using sc_dt::int64;/d' /usr/local/systemc-2.3.3q/include/systemc.h
        - cd ../..
        - cd Software
        - mkdir build
        - cd build
        - cmake ..

script: make
